version: '3'

services:
   db:
     image: mysql:5.7
     ports:
      - "3306:3306"
     restart: always
     volumes:
       - ./db-backup:/db-backup
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: mattiashem/wp-base:s1https
         #image: mattiashem/wp-base:latest
         #image: wordpress:4.9.8-php5.6-apache
     ports:
       - "80:8000"
       - "443:8443"
     restart: always
     volumes:
       - ./:/repo/wp-content
     environment:
       DBHOST: db
       SITENAME: wordpress
       DBPASS: wordpress
       SMTP_HOST: mailgun.com
       SMTP_USER: non@test.com
       SMTP_PASS: password
       SMTP_FROM: non@test.com
   dbseed:
     depends_on:
       - db
     image: mattiashem/dbseed
     volumes:
       - ./seed:/seed
     environment:
       - SQLUSER=wordpress
       - SQLPASS=wordpress
       - SQLDB=wordpress

