FROM mattiashem/wp-base:latest
USER root
RUN apt-get -y update
RUN apt-get install -y dialog apt-utils
RUN rm /etc/php/7.2/fpm/php.ini
RUN apt-get install -y php7.2-mbstring

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN php wp-cli.phar --info
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
USER www-data
#RUN wp core update --version=5.3.1

COPY nginx.conf /etc/nginx/nginx.conf

RUN /etc/init.d/nginx restart